spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            client-secret: 
      resourceserver:
        jwt:
          issuer-uri: accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs