spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1064271532168-6ergcqf55tbv8n2ar5d08rsfqml6ntkr.apps.googleusercontent.com
            client-secret: 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
      resourceserver:
        jwt:
          issuer-uri: accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs